### ISSUE TITLE
Two-day event leads to bot crash

### ISSUE THREAD

**Issue by NereySer** [NereySer/tbgc#157]
How to reproduce: create an event in next week that starts at 20:00 at one day and ends at 01:00 at the next day

Expected behavior: pre-messages at route / displays correct messages (20:00-01:00), at correct time  arrives correct message

Actual behavior: route / crashes

After fixing create new issue to cover events that continue more than 2 days

**Comment by NereySer** [comment]
It seems like it's a feature. Whatever, should be fixed

```
[ERROR]	2024-01-06T13:58:27.104Z	eb0a4725-23c7-4687-a8e2-38864e2a53eb	Exception on / [GET]
Traceback (most recent call last):
  File "/var/task/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/task/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/task/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/task/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "./api/main.py", line 52, in show_next_notifications
    notification.time = time_checks.whenTimeToRemind(events)
  File "/var/task/modules/time_checks.py", line 83, in whenTimeToRemind
    test_time = whenHourToRemind(events, test_time)
  File "/var/task/modules/time_checks.py", line 67, in whenHourToRemind
    if isItTimeToRemind(events, test_time)[0]:
  File "/var/task/modules/time_checks.py", line 51, in isItTimeToRemind
    first_event_datetime = checkEvents(events)
  File "/var/task/modules/time_checks.py", line 30, in checkEvents
    raise Exception("Events in different days are not allowed")
Exception: Events in different days are not allowed
```

**Comment by NereySer** [comment]
It's interesting, but two-day event successfully sent

```
<html>
  <body>
    <p>Time bounds: 2024-01-07 12:00:17.828966+03:00 - 2024-01-07 23:59:59+03:00</p>
    <p>Last event notify time: 2024-01-08 00:00:00+03:00</p>

      Events date: 2024-01-07 12:00:17.828966+03:00
        <p>2024-01-07 19:30:00+03:00-2024-01-08 12:00:00+03:00 () -  тест</p>
    
    <p>Last event time: </p>
    <p>Time to remind: True</p>
  </body>
</html>
```
